### ISSUE TITLE
Actors disapeared with MxKineticScrollView and MxViewport.

### ISSUE THREAD

**Issue by cfsghost** [clutter-project/mx#43]
Now I have created a ClutterGroup container object which includes a lot actors, then try to put it in MxViewport to make it can be scrollable. But the problem is, actors disapeared if its position(x, y) is not in the current screen area. 

 ex, scrollview size is 800x600, group object size is 2000x600. actor will disapear if its X axis position > 801.

If it's not a bug, how can I make it appear when I scroll with MxKineticScrollView?

**Comment by cfsghost** [comment]
Well, I've tried disable-culling, it works well:

CLUTTER_PAINT=disable-culling

**Comment by ebassi** [comment]
as said on IRC, ClutterGroup doesn't know anything about being inside a scrollable container - it's an Mx concept; the paint volume of the Group will go outside the parent, and the culling system inside ClutterActor will discard the Group - as intended.

Mx containers implementing the Scrollable interface take that into consideration, and modify their paint volume to take into account the translation; if we wanted to allow any Actor to be scrollable then we need to move MxScrollable and MxAdjustment into Clutter.

there's also the option of pulling a gtk+, and adding a MxViewport widget that just modifies the paint volume of itself to compensate for the scrolling, and a add_with_viewport() method to MxKineticScrollView and MxScrollView that automatically can wrap every non-scrollable actor into a scrollable viewport; this solution could work as an interim option until Clutter has a scrollable actor API.

**Comment by thos** [comment]
I suspect this is because MxViewport does not implement get_paint_volume.

**Comment by cfsghost** [comment]
If so, I suggest it's better to Implement get_paint_volume for MxViewport. I cannot find way to solve this problem, to scroll it with Mx Widget.

**Comment by thos** [comment]
I've have pushed a series of patches to fix this to the master and mx-1.4 branches. The fix actually involved changing the clipping behaviour slightly as well as implementing get_paint_volume.

**Comment by mmdemo** [comment]
"Actors disapeared with MxKineticScrollView and MxViewport"
In the case u have mentioned,allocation is not called for ur actors from scrollview->viewport->myactor which is done internally in mx library. 

Here is suggestion to make it appear.
ClutterActor *view = mx_viewport_new();
ClutterActor *scroll = mx_XYZ(); 
mx_bin_set_child(sroll,view);//instead of clutter_actor_add_child or clutter_container_add_actor()
mx_bin_set_child(view,cont).//instead of clutter_actor_add_child or clutter_container_add_actor()

I hope this will solve ur problem
