### ISSUE TITLE
mx master branch fails to build

### ISSUE THREAD

**Issue by jpwhiting** [clutter-project/mx#7]
when trying to build mx master branch, it gives an error from a warning about tests/test-widgets.c:266 create_combo_box not having been declared previously.  Adding a declaration right above it fixes compilation like so:

index 99f204b..58da82e 100644
--- a/tests/test-widgets.c
+++ b/tests/test-widgets.c
@@ -266,6 +266,9 @@ change_widget (MxComboBox *box,
 }

 ClutterActor*
+create_combo_box ();
+
+ClutterActor*
 create_combo_box ()
 {
   ClutterActor *combo;

Alternatively, maybe that warning should be disabled, or there's another way to not use MX_MAINTAINER_CFLAGS when building that I didn't see?

**Comment by thos** [comment]
This is an important warning because it can identify symbols that are either missing from the headers or not marked as static. In this particular case, the function should be marked as static.

The --enable-maintainer-flags option has now been enabled by default when running autogen.sh, which adds this warning and also -Werror. However, -Werror should probably be removed from the maintainer flags now that it is enabled from autogen.sh.

**Comment by thos** [comment]
This is now fixed in master.
